common_app/urls.py
from django.urls import path
from . import views
app_name='common_app'


urlpatterns=[
    path('',views.common_app_index,name='home'),
   
    path('about',views.common_app_about,name='about'),
    path('contact',views.common_app_contact,name='contact'),
    path('patient_click',views.common_app_patient_click,name='patient_click'),
    path('patient_login',views.common_app_patient_login,name='patient_login'),
    path('patient_register',views.common_app_patient_register,name='patient_register'),
    path('doctors_login',views.common_app_doctors_login,name='doctors_login'),
    path('doctors_register',views.common_app_doctors_register,name='doctor_register'),
    path('doc_logincheck/<int:doctor_id>/',views.common_app_doc_logincheck, name='doc_logincheck'),



    path('department',views.common_app_department,name='department'),
    path('doctors',views.common_app_doctors,name='doctors'),
    path('doctor_click',views.common_app_doctor_click,name='doctor_click'),
    path('admin_click',views.common_app_admin_click,name='admin_click'),
    path('admin_register',views.common_app_admin_register,name='admin_register'),
    path('admin_login',views.common_app_admin_login,name='admin_login'),
    
    path('checkemail',views.check_email,name='check_email'),
    path('checkemail_doctor',views.check_email_admin,name='check_email_admin'),
    path('checkemail_admin',views.check_email_doctor,name='check_email_doctor'),

    
]

doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'


urlpatterns=[
    path('base',views.doctor_base,name='base'),
    path('index',views.doctor_index,name='index'),


    path('appointments',views.doctor_appointments,name='appointments'),
   
    path('delete_appointment',views.doctor_delete_appointment,name='delete_appointment'),
    path('remove_appointment/<int:d_id>',views.remove_appointment,name='remove_app'),

    path('patient_page',views.doctor_patient_page,name='patient_page'),
    path('patient_record',views.doctor_patient_record,name='patient_record'),
    path('patient_booked',views.doctor_patient_booked,name='patient_booked'),
  
    path('view_prescription/<int:booking_id>',views.doctor_view_prescription,name='view_prescription'),

    path('change_password',views.doctor_change_password,name='change_password'),
    path('doctor_profile',views.doctor_doctor_profile,name='doctor_profile'),

    path('view_appointment/', views.doctor_view_appointment, name='view_appointment'),
    path('add_prescription/<int:b_id>/',views.add_prescription,name='add_prescription'),
    path('doctor/prescription/<int:booking_id>/',views.doctor_prescription,name='prescription'),
    path('delete_item/<int:booking_id>/',views.delete_item,name='delete_item'),
    path('edit_item/<int:booking_id>/',views.edit_item,name='edit_item'),
    path('update_item/<int:booking_id>/',views.update_item,name='update_item'),
    path('consultation',views.doctor_consultation,name='consultation'),
    path('update_consultation_status',views.update_consultation_status,name='update_consultation_status'),



    path('doctor_logout',views.doctor_logout,name='doctor_logout'),
]

hospital_management/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common_app.urls')),
    path('patient/', include('patient.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('doctor/', include('doctor.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views
app_name='patient'


urlpatterns=[
    path('index',views.patient_index,name='index'),
    path('doc_booking',views.patient_doc_booking,name='booking'),
    path('profile',views.patient_profile,name='profile'),
    path('booked',views.patient_booked,name='booked'),

    path('your_bookings',views.patient_your_bookings,name='your_bookings'),
    path('prescription_list',views.patient_prescription_list,name='prescription_list'),
    path('view_bookings',views.patient_view_bookings,name='view_bookings'),
    path('pat_doctors',views.patient_pat_doctors,name='pat_doctors'),

    path('doctor_search',views.doctorSearchAjax,name='doctor_search'),
    path('searchdoctor',views.searchdoctor,name='searchdoctor'),


    path('view_search_result/<int:d_id>/',views.patient_view_search_result,name='search_result'),
   



    path('consultation_details/<int:consultation_id>/', views.patient_consultation_details, name='consultation_details'),
    path('change_password',views.patient_change_password,name='change_password'),
  
    path('view_prescription/<int:booking_id>/',views.patient_view_prescription,name='view_prescription'),

    path('patient_logout',views.patient_logout,name='patient_logout'),
]

common_app/models.py
from django.db import models


# Create your models here.

class Patient(models.Model):
    patient_name = models.CharField(max_length=50)
    patient_mobile = models.BigIntegerField()
    patient_address = models.CharField(max_length=200)
    patient_email = models.CharField(max_length=40)
    patient_password = models.CharField(max_length=10,default='')
    status = models.CharField(max_length=20, default='active')

    class Meta:
        db_table = 'patient'


class Departments(models.Model):
    dep_name = models.CharField(max_length=100)
    dep_description = models.TextField()
    dep_image = models.ImageField(upload_to='department/')

    class Meta:
        db_table = 'department'


class Doctors(models.Model):
    doctor_name = models.CharField(max_length=50)
    doctor_email = models.CharField(max_length=40)
    doctor_department = models.ForeignKey(Departments,on_delete=models.CASCADE)
    doctor_phone = models.BigIntegerField()
    doctor_address = models.CharField(max_length=200)
    user_name = models.IntegerField(default=0)
    password = models.CharField(max_length=40, default='')
    doctor_gender = models.CharField(max_length=15)
    doctor_image = models.ImageField(upload_to='doctor/',default='static/images/dummy-user.png')
    status = models.CharField(max_length=20, default='pending')

    class Meta:
        db_table = 'doctors'


class Admin(models.Model):
    admin_name = models.CharField(max_length=40)
    admin_email =  models.CharField(max_length=40)
    admin_password = models.CharField(max_length=10,default='')

    class Meta:
        db_table = 'admin'


class Contact(models.Model):
    name = models.CharField(max_length=40)
    phone = models.BigIntegerField()
    remark = models.CharField(max_length=300)

    class Meta:
        db_table = 'contact'

doctor/models.py
from django.db import models

from patient.models import Booking

# Create your models here.


class Prescription(models.Model):
    booking = models.ForeignKey(Booking,on_delete=models.CASCADE)
    
    diagnosis = models.CharField(max_length=300)
    medication_name =  models.CharField(max_length=50)
    purpose = models.CharField(max_length=50)
    dosage = models.CharField(max_length=40)
    route = models.CharField(max_length=30)
    frequency = models.CharField(max_length=50)
    status = models.CharField(max_length=20, default='active')

    class Meta:
        db_table = 'prescriptions'

    

common_app/views.py
from audioop import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from.models import Admin, Contact, Departments, Doctors, Patient
from django.http import JsonResponse
from django.contrib.auth import authenticate, login

# Create your views here.

def common_app_index(request):
    return render(request,'common_app_templates/index.html')



def common_app_about(request):
    return render(request,'common_app_templates/about.html')

def common_app_contact(request):
    msg = ''
    if request.method == 'POST':
        pname = request.POST['name']
        pmobile = request.POST['mobile'] 
        premark = request.POST['remark'] 
        client = Contact(name = pname, phone = pmobile, remark = premark)
        client.save()
        msg = 'Message Send!'

    return render(request,'common_app_templates/contact.html',{'message':msg})



# ////////////////////////Patient section///////////////////////////////////////

def common_app_patient_click(request):
    return render(request,'common_app_templates/patient_click.html')

def common_app_patient_login(request):
    msg = ''
    if request.method == 'POST':
        email = request.POST['p_email']
        password = request.POST['p_password'] 

        try:
            patient = Patient.objects.get(patient_email = email, patient_password = password)
            request.session['patient'] = patient.id
            print(request.session['patient'])
            return redirect('patient:index')
        except:
            msg = 'Email or Password is incorrect'
    return render(request,'common_app_templates/patient_login.html',{'message':msg})

def common_app_patient_register(request):
    
    msg2 = ''
    if request.method == 'POST':
        pat_name = request.POST['p_name']
        pat_mobile = request.POST['p_mobile']
        pat_address = request.POST['p_address']
        pat_email = request.POST['p_email']
        pat_password = request.POST['p_password']
        email_exist = Patient.objects.filter(patient_email = pat_email).exists()
        if not email_exist:

            patient = Patient(patient_name = pat_name, patient_mobile = pat_mobile, patient_address = pat_address, patient_email= pat_email, patient_password= pat_password)
            patient.save()
            msg2 = 'You are Successfully Registred !'

       
        
    return render(request,'common_app_templates/patient_register.html',{'message2':msg2})


def check_email(request):  #checking email of patient
    email = request.POST['p_email']
    print(email)
    email_exist =Patient.objects.filter(patient_email=email).exists()
    if not email_exist:
        status = False
    else:
        status = True
    return JsonResponse({'email_exist': status})

def check_email_admin(request): # checking email of admin
    email = request.POST['a_email']
    print(email)
    email_exist =Admin.objects.filter(admin_email=email).exists()
    if not email_exist:
        status = False
    else:
        status = True
    return JsonResponse({'email_exist': status})

def check_email_doctor(request): # checking email of admin
    email = request.POST['doc_email']
    print(email)
    email_exist =Doctors.objects.filter(doctor_email=email).exists()
    if not email_exist:
        status = False
    else:
        status = True
    return JsonResponse({'email_exist': status})


def common_app_doctor_click(request):
    return render(request,'common_app_templates/doctor_click.html')

def common_app_doctors_login(request):
    msg=''
    if request.method == 'POST':
        
        username = request.POST['user_name']
        password = request.POST['password']

        try:
            doctor = Doctors.objects.get(user_name = username,password = password)
            request.session['doctor'] = doctor.id
            print( request.session['doctor'])
            return redirect('doctor:index')
            
        except Exception as e:
            
            msg = 'username or password not match'
            print( "username or password not match")
    return render(request,'common_app_templates/doctors_login.html',{'message':msg})



def common_app_doctors_register(request):
    msg1=''
    msg2=''
    if request.method == 'POST':
        d_name = request.POST['doc_name']
        d_email = request.POST['doc_email']
        
        d_phone = request.POST['doc_phone']
        d_address = request.POST['doc_address']
        d_gender = request.POST['doc_gender']

        dep = request.POST['doc_department']

        if 'doc_image' in request.FILES:
            d_image = request.FILES['doc_image']
            
            doctor = Doctors(doctor_name = d_name, doctor_email = d_email, doctor_department_id = dep, doctor_phone = d_phone, doctor_address = d_address, doctor_gender = d_gender, doctor_image = d_image)
        else:
            doctor = Doctors(doctor_name = d_name, doctor_email = d_email, doctor_department_id = dep, doctor_phone = d_phone, doctor_address = d_address, doctor_gender = d_gender)
        doctor.save()
        msg1 = 'You are Successfully Registred'
        return redirect('common_app:doc_logincheck', doctor_id=doctor.id)
    dep = Departments.objects.all()
    return render(request,'common_app_templates/doctors_register.html',{'departments':dep , 'message1':msg1, 'message2':msg2})

def common_app_doc_logincheck(request,doctor_id): # for name
    doctor = Doctors.objects.get( id=doctor_id)
    return render(request,'common_app_templates/doc_logincheck.html', {'doctor': doctor})


def common_app_department(request):
    dic_dept = Departments.objects.all()
    for dept in dic_dept:

        dept.image_url = dept.dep_image.url

    return render(request,'common_app_templates/department.html', {'dic_dept':dic_dept})


def common_app_doctors(request):
    doctor = Doctors.objects.filter(status = 'approved')
    for doc in doctor:

        doc.image_url = doc.doctor_image.url
    return render(request,'common_app_templates/doctors.html',{'doctors':doctor})

def common_app_admin_register(request):
    msg = ''
    if request.method == 'POST':
        adm_name = request.POST['a_name']
        adm_email = request.POST['a_email']
        adm_password = request.POST['a_password']
        email_exist = Admin.objects.filter(admin_email = adm_email).exists()
        if not email_exist:

            admin = Admin(admin_name = adm_name, admin_email= adm_email, admin_password = adm_password)
            admin.save()
            msg = 'You are Successfully Registred !'
            # return redirect('common_app:admin_success')
            
    return render(request,'common_app_templates/admin_register.html',{'message':msg})

def common_app_admin_login(request):
    msg = ''
    if request.method == 'POST':
        email = request.POST['ad_email']
        password = request.POST['ad_password'] 

        try:
            admin = Admin.objects.get(admin_email = email, admin_password = password)
            request.session['admin'] = admin.id
            print(request.session['admin'])
            return redirect('admin_app:index')
        except:
            msg = 'Email or Password is incorrect'
   
    return render(request,'common_app_templates/admin_login.html',{'message':msg})



def common_app_admin_click(request):
    return render(request,'common_app_templates/admin_click.html')


     
    

    
    
        
  

common_app/templates/common_app_templates/admin_click.html
{% extends 'common_app_templates/base.html' %}
{% load static %}

{% block header %}



{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<br><br><br>

<!-- patient signup/login page -->

<section style="background-color: lightblue;
    margin-bottom: -49px;
    margin-top: -11px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center" style="margin-top: 85px;margin-bottom: 85px;">
                <h1 style="font-weight: 300;font-size: 50px;letter-spacing: 2px;">Hello, Admin</h1>
                <p style="font-size: 19px;font-weight: 300;letter-spacing: 3px;margin-top: 17px;margin-bottom: 25px;">
                    Welcome to National Hospital</p>
                <hr>
                <p>You can access various features after Login/SignUp</p>
                <div>
                    <button type="button" class="btn btn-primary me-3"><a href="{% url 'common_app:admin_register' %}"
                            style="color: #fff;text-decoration: none;">SignUp</a></button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'common_app:admin_login' %}"
                            style="color: #fff;text-decoration: none;">Login</a></button>
                </div>

            </div>
        </div>
    </div>
</section>







<!-- footer -->

{% endblock %}

common_app/templates/common_app_templates/admin_register.html
{% extends 'common_app_templates/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/style_register.css' %}">
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM="
    crossorigin="anonymous"></script>
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}



<section id="main_body">

    <div class="heading" style="padding-top: 200px;">
        <h1 class="heading_text text-center mb-2"><u>Admin Register here</u> </h1>
    </div>


    <div>
        <h6 style="    text-align: center;font-size: 22px;font-weight: 400;color: greenyellow;">{{message}}</h6>
    </div>


    <section id="reg_form" style="margin-bottom: -50px;">
        <div class="container">
            <div class="row justify-content-center mt-5">
                <div class="col-xs-12 col-sm-8 col-md-6 col-lg-5">
                    <div class="card" style="box-shadow: 12px 12px 22px;">
                        <div class="card-header">
                            <h5 class="card-title">Admin Register</h5>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="">Name</label>
                                    <input type="text" class="form-control" placeholder="Name" name="a_name" />
                                </div>


                                <div class="form-group">
                                    <label for="">Email</label>
                                    <input type="email" id="email" class="form-control" placeholder="Email/Username"
                                        name="a_email" />
                                    <span id="email_check"></span>


                                </div>

                                <div class="form-group">
                                    <label for="">Password</label>
                                    <input type="password" class="form-control" placeholder="Password"
                                        name="a_password" />

                                </div>



                                <button class="btn form-control mt-3" id="btnColor" style="color: #fff;"
                                    data-target="#mymodel" data-toggle="modal">
                                    Register
                                </button>

                                <p style="text-align: center; color: green;">{{message}}</p>




                            </form>

                            <br>
                            <p class="text-left" style="font-size:15px">If you already have an account, <a
                                    href="/admin_login">login</a> instead.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</section>





<script>
    $('#email').change(function () {

        console.log($(this).val())
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val() //passing csrf token in ajax request
            }
        })

        $.ajax({
            type: 'POST',
            url: "{% url 'common_app:check_email_admin' %}",
            data: {
                'a_email': $(this).val(),

            },
            success: function (response) {
                if (response.email_exist == true) {
                    $('#email_check').html('Email already registerd.').css("color", "red")
                    $('#btnColor').prop('disabled', true)
                }
                else {
                    $('#email_check').html('Email available for register.').css("color", "green")
                    $('#btnColor').prop('disabled', false)

                }
                console.log(response.email_exist)
            }
        })
    })
</script>




{% endblock %}

common_app/templates/common_app_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    {% block header %}

    {% endblock %}

    <title>{% block title %}base{% endblock %}</title>
</head>

<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-xl navbar-dark fixed-top" style="background-color: black;">
        <div class="container">

            <a class="navbar-brand fs-2 fw-bold" href="#"><span class="text-danger">National</span>&nbsp; Hospital</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark"
                aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse show" id="navbarDark">
                <ul class="navbar-nav ms-auto mb-2 mb-xl-0 fs-5 ms-auto p-2 text-center">
                    <li class="nav-item me-3">
                        <a class="nav-link active " aria-current="page" href="{% url 'common_app:home' %}">Home</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'common_app:department' %}" style="color: #fff;">Department</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'common_app:doctors' %}" style="color: #fff;">Doctors</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'patient:booking' %}" style="color: #fff;">Booking</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'common_app:about' %}" style="color: #fff;">About Us</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link" href="{% url 'common_app:contact' %}" style="color: #fff;">Contact Us</a>
                    </li>
                    <!-- <li class="nav-item me-3">
                        <a class="nav-link" href="#">User Login</a>
                    </li> -->
                    <li>
                        <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                User Login
                            </a>

                            <ul class="dropdown-menu drop" style="background-color: black; text-align: center;">
                                <li><a class="dropdown-item" href="{% url 'common_app:admin_click' %}">Admin</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'common_app:doctor_click' %}">Doctor</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'common_app:patient_click' %}">Patient</a>
                                </li>
                            </ul>
                        </div>

                    </li>



                </ul>

            </div>

        </div>
    </nav>
    <!-- Header Ends -->


    <!-- footer -->
    {% block content %}{% endblock %}

    <footer class="mt-5 pt-5 pb-5 footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-xs-12">
                    <a class="navbar-brand fs-2 fw-bold" href="#"><span class="text-danger">National</span>&nbsp;
                        Hospital
                    </a>
                    <p>Established in 2014, National Hospital is leading the healthcare industry with its
                        superlative, patient-centric,
                        all-embracing, and world-class orthopaedic services. Therefore, we are recognized as one of the
                        best
                        orthopaedic
                        hospitals in India offering quality healthcare to the masses in, Kerala and promotion of health
                        tourism.</p>
                    <ul class="social">
                        <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                        <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                        <li><a href="#"><i class="bi bi-whatsapp"></i></a></li>
                        <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-xs-12 links">
                    <h4 class="mt-lg-0 mt-sm-3">Quick Links</h4>
                    <ul class="m-0 p-0">
                        <li><a href="{% url 'common_app:home' %}">Home</a></li>
                        <li><a href="{% url 'common_app:department' %}">Department</a></li>
                        <li><a href="{% url 'common_app:doctors' %}">Doctors</a></li>
                        <li><a href="{% url 'patient:booking' %}">Booking</a></li>
                        <li><a href="{% url 'common_app:about' %}">About Us</a></li>
                        <li><a href="{% url 'common_app:contact' %}">contact Us</a></li>

                    </ul>

                </div>
                <div class="col-lg-4 col-xs-12 Location">
                    <h4 class="mt-lg-0 mt-sm-4">Location</h4>
                    <p><i class="bi bi-geo-alt-fill">&nbsp Building No. 38/2208-B Karaparamba – Kunduparamba, &nbsp
                            &nbsp&nbsp&nbsp&nbsp Mini Bypass
                            Rd,Edakkad, Kerala 673005, India.
                        </i>
                    </p>
                    <p><i class="bi bi-telephone">&nbsp +91 495 712 3456</i></p>
                    <p><i class="bi bi-envelope-fill">&nbsp info@national.com</i></p>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col copyright text-center">
                    <p>
                        <small class="text-white-50">
                            Ⓒ 2022 National. All Right Reserved
                        </small>
                    </p>
                </div>

            </div>
        </div>

    </footer>



</body>

</html>

common_app/templates/common_app_templates/doc_logincheck.html
{% extends 'common_app_templates/base.html' %}
{% load static %}

{% block header %}
<style>
    .content {
        margin-top: 6rem
    }

    .content h1 {
        font-weight: 400;
        margin-bottom: 22px;
        font-size: 55px;
    }

    .content p {
        letter-spacing: 1px;
        color: goldenrod;
        font-size: 18px;
    }

    .bottom_content {
        margin-top: 31px;
    }

    .bottom_content button a {
        text-decoration: none;
        color: #fff;
    }

    .bottom_content button {
        background-color: blue;
        border: none;
        border-radius: 5px;
        width: 150px;
        height: 32px;
    }
</style>


{% endblock %}

{% block title %}doc_logincheck{% endblock %}
{% block content %}

<br><br><br>
<section>
    <div class="container">
        <div class="col-lg-12">
            <div class="content text-center">
                <h1>Hello {{ doctor.doctor_name|title }}</h1>
                <p>Your Account is not approved till now</p>
                <p>Our Team is checking your profile</p>
                <p>Soon your Account will be confirmed!!!</p>
            </div>
            <hr>
            <div class="bottom_content text-center">
                <h6>Check Later</h6>
                <button><a href="{% url 'common_app:home' %}">Go Back For Now</a></button>
            </div>

        </div>
    </div>
</section>






<!-- footer -->

{% endblock %}

common_app/templates/common_app_templates/doctor_click.html
{% extends 'common_app_templates/base.html' %}
{% load static %}

{% block header %}



{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<br><br><br>

<!-- patient signup/login page -->

<section style="background-color: lightblue;
    margin-bottom: -49px;
    margin-top: -11px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center" style="margin-top: 85px;margin-bottom: 85px;">
                <h1 style="font-weight: 300;font-size: 50px;letter-spacing: 2px;">Hello, Doctor</h1>
                <p style="font-size: 19px;font-weight: 300;letter-spacing: 3px;margin-top: 17px;margin-bottom: 25px;">
                    Welcome to National Hospital</p>
                <hr>
                <p>You can access various features after Login/SignUp</p>
                <div>
                    <button type="button" class="btn btn-primary me-3"><a href="{% url 'common_app:doctor_register' %}"
                            style="color: #fff;text-decoration: none;">SignUp</a></button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'common_app:doctors_login' %}" style="color: #fff;text-decoration: none;">Login</a></button>
                </div>

            </div>
        </div>
    </div>
</section>







<!-- footer -->

{% endblock %}

common_app/templates/common_app_templates/patient_click.html
{% extends 'common_app_templates/base.html' %}
{% load static %}

{% block header %}


{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}

<br><br><br>

<!-- patient signup/login page -->

<section style="background-color: lightblue;
    margin-bottom: -49px;
    margin-top: -11px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center" style="margin-top: 85px;margin-bottom: 85px;">
                <h1 style="font-weight: 300;font-size: 50px;letter-spacing: 2px;">Hello, Patient</h1>
                <p style="font-size: 19px;font-weight: 300;letter-spacing: 3px;margin-top: 17px;margin-bottom: 25px;">
                    Welcome to National Hospital</p>
                <hr>
                <p>You can access various features after Login/SignUp</p>
                <div>
                    <button type="button" class="btn btn-primary me-3"><a href="{% url 'common_app:patient_register' %}"
                            style="color: #fff;text-decoration: none;">SignUp</a></button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'common_app:patient_login' %}"
                            style="color: #fff;text-decoration: none;">Login</a></button>
                </div>

            </div>
        </div>
    </div>
</section>







<!-- footer -->

{% endblock %}