doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'


urlpatterns=[
    path('base',views.doctor_base,name='base'),
    path('index',views.doctor_index,name='index'),


    path('appointments',views.doctor_appointments,name='appointments'),
   
    path('delete_appointment',views.doctor_delete_appointment,name='delete_appointment'),
    path('remove_appointment/<int:d_id>',views.remove_appointment,name='remove_app'),

    path('patient_page',views.doctor_patient_page,name='patient_page'),
    path('patient_record',views.doctor_patient_record,name='patient_record'),
    path('patient_booked',views.doctor_patient_booked,name='patient_booked'),
  
    path('view_prescription/<int:booking_id>',views.doctor_view_prescription,name='view_prescription'),

    path('change_password',views.doctor_change_password,name='change_password'),
    path('doctor_profile',views.doctor_doctor_profile,name='doctor_profile'),

    path('view_appointment/', views.doctor_view_appointment, name='view_appointment'),
    path('add_prescription/<int:b_id>/',views.add_prescription,name='add_prescription'),
    path('doctor/prescription/<int:booking_id>/',views.doctor_prescription,name='prescription'),
    path('delete_item/<int:booking_id>/',views.delete_item,name='delete_item'),
    path('edit_item/<int:booking_id>/',views.edit_item,name='edit_item'),
    path('update_item/<int:booking_id>/',views.update_item,name='update_item'),
    path('consultation',views.doctor_consultation,name='consultation'),
    path('update_consultation_status',views.update_consultation_status,name='update_consultation_status'),



    path('doctor_logout',views.doctor_logout,name='doctor_logout'),
]

hospital_management/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common_app.urls')),
    path('patient/', include('patient.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('doctor/', include('doctor.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

doctor/models.py
from django.db import models

from patient.models import Booking

# Create your models here.


class Prescription(models.Model):
    booking = models.ForeignKey(Booking,on_delete=models.CASCADE)
    
    diagnosis = models.CharField(max_length=300)
    medication_name =  models.CharField(max_length=50)
    purpose = models.CharField(max_length=50)
    dosage = models.CharField(max_length=40)
    route = models.CharField(max_length=30)
    frequency = models.CharField(max_length=50)
    status = models.CharField(max_length=20, default='active')

    class Meta:
        db_table = 'prescriptions'

    

doctor/views.py
from audioop import reverse
from multiprocessing import context
from pyexpat.errors import messages
from django.forms import ValidationError
from django.shortcuts import redirect, render
from admin_app.models import Consultation
from common_app.models import Departments, Doctors, Patient
from doctor.decorators import auth_doctor
from doctor.models import Prescription
from django.http import HttpResponse, JsonResponse
from patient.models import Booking
from django.contrib import messages

# Create your views here.
@auth_doctor
def doctor_base(request):
    
    return render(request,'doctor_templates/base.html')


@auth_doctor
def doctor_index(request):
    doctor = Doctors.objects.filter(id = request.session['doctor']).values('doctor_name','doctor_image')
    print(doctor)
    doctor_name = doctor[0]['doctor_name']
    doctor_pic = doctor[0]['doctor_image']




    doctor = Doctors.objects.get(id = request.session['doctor'])
    total_patients = Booking.objects.filter(doctor_name=doctor).count()
    consulted = Booking.objects.filter(doctor_name=doctor, status='consulted').count()
    booked = Booking.objects.filter(doctor_name=doctor, status='booked').count()



    appointments = Booking.objects.filter(doctor_name=doctor, status='booked' ).order_by('-booking_date')[0:5]
    recent_appointments = {}
    for appoint in appointments:
        if appoint.patient_email in recent_appointments:
            if appoint.booking_date > recent_appointments[appoint.patient_email].booking_date:

                recent_appointments[appoint.patient_email] = appoint
        else:
            recent_appointments[appoint.patient_email] = appoint
    recent_appointments_list = list(recent_appointments.values())

    context = {
        'd_name': doctor_name,
        'd_image': doctor_pic,
        'total_patients':total_patients,
        'recent_apponitments': recent_appointments_list,
        'consulted':consulted,
        'booked':booked
    }

    return render(request,'doctor_templates/index.html',context)


@auth_doctor
def doctor_patient_page(request):
    return render(request,'doctor_templates/patient_page.html',)

@auth_doctor
def doctor_patient_booked(request):
    doctor = Doctors.objects.get(id = request.session['doctor'])
    booked_patients = Booking.objects.filter(doctor_name = doctor, status = 'booked')
    return render(request,'doctor_templates/patient_booked.html',{'booked_patients':booked_patients})



@auth_doctor
def doctor_patient_record(request):
    doctor = Doctors.objects.get(id = request.session['doctor'])
    
    patient_record = Booking.objects.filter(doctor_name = doctor, status = 'consulted')
    
    return render(request,'doctor_templates/patient_record.html',{'patients':patient_record})



@auth_doctor   
def doctor_view_prescription(request,booking_id):
    booked_patient = Booking.objects.get(id=booking_id)
    
    prescript = Prescription.objects.filter(booking_id=booking_id)
    return render(request,'doctor_templates/view_prescription.html',{'pre':prescript,'book':booked_patient})


@auth_doctor
def doctor_change_password(request):
    error_msg = ''
    success_msg = ''

    if request.method == 'POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        if new_password == confirm_password:
            if len(new_password) >= 8:
                doctor = Doctors.objects.get(id = request.session['doctor'])
                if doctor.password == old_password:

                    doctor.password = new_password
                    doctor.save()
                    success_msg = 'Password changed successfully'
                else:
                    error_msg = 'Incorrect Password'
            else:
                error_msg = 'Password should be 8 charecters long'
            
        else:
            error_msg = 'Password doesn\'t match'
    
    return render(request,'doctor_templates/change_password.html',{'error_message' : error_msg, 'success_message': success_msg})


@auth_doctor
def doctor_doctor_profile(request):
    profile = Doctors.objects.filter(id = request.session['doctor'])
   

    if request.method == 'POST':
        
        new_name = request.POST['name']
        new_phone = request.POST['phone']
        new_address = request.POST['address']
        new_email = request.POST['email']
        new_gender = request.POST['pat_gender']
        new_department_id = int(request.POST['department'])
        new_department = Departments.objects.get(id=new_department_id)
        
        doctor = Doctors.objects.get(id = request.session['doctor'])#.update(patient_name = new_name,patient_mobile = new_phone, patient_address = new_address, patient_email = new_email)
        doctor.doctor_name = new_name
        doctor.doctor_phone  = new_phone
        doctor.doctor_address  = new_address
        doctor.doctor_address  = new_email
        doctor.doctor_department = new_department 
        doctor.doctor_gender = new_gender
    

        doctor.save()
        msg = "Update Successfully!"
    new_department = Departments.objects.all()
    return render(request,'doctor_templates/doctor_profile.html',{'profile':profile, 'departments':new_department})


def doctor_delete_appointment(request):
   doctor = Doctors.objects.get(id = request.session['doctor'])
   appointment = Booking.objects.filter(doctor_name = doctor,status = 'booked')
   return render(request,'doctor_templates/delete_appointment.html',{'appointments':appointment})
def remove_appointment(request,d_id):
    app_list = Booking.objects.get(id = d_id)
    app_list.delete()
    return redirect('doctor:delete_appointment')


@auth_doctor
def doctor_appointments(request):
    return render(request,'doctor_templates/appointments.html')

@auth_doctor
def doctor_view_appointment(request):
    doctor = Doctors.objects.get(id = request.session['doctor'])
    appointment = Booking.objects.filter(doctor_name = doctor,status = 'booked')
    return render(request, 'doctor_templates/view_appointment.html', {'appointments':appointment})



@auth_doctor
def add_prescription(request,b_id):
    
    doctor = Doctors.objects.get(id = request.session['doctor'])
    return redirect('doctor:prescription')



@auth_doctor
def doctor_prescription(request, booking_id):
    msg = ''
    bkng = Booking.objects.get(id=booking_id)
    
    
    if request.method == 'POST':
        print('test.............................')
        
        pdiagnosis = request.POST['p_diagnosis']
        pname = request.POST['p_name']
        ppurpose = request.POST['p_purpose']
        pdosage = request.POST['p_dosage']
        proute = request.POST['p_route']
        pfrequency = request.POST['p_frequency']
        prescription = Prescription(booking=bkng, diagnosis=pdiagnosis, medication_name=pname, purpose=ppurpose, dosage=pdosage, route=proute, frequency=pfrequency)
        prescription.status = 'consulted'
        
        prescription.save()
        bkng.status = 'consulted'
        bkng.save()
        msg = 'Prescription added successfully'
        
        
    prescription_list = Prescription.objects.filter(booking=bkng)
    print(prescription_list)
    return render(request, 'doctor_templates/prescription.html', {'message1': msg, 'list': prescription_list, 'booking': bkng})

def delete_item(request,booking_id):
    item = Prescription.objects.get(id = booking_id)
    item.delete()
    messages.success(request, 'One prescription removed')
    return redirect('doctor:prescription', booking_id=item.booking_id)

def edit_item(request,booking_id):
    ed_item = Prescription.objects.get(id = booking_id)
    bkng = Booking.objects.get(id=ed_item.booking.id)
    prescription_list = Prescription.objects.filter(booking=bkng)
    context = {
        'ed_item':ed_item,
        'prescription_list':prescription_list
    }
    
    return render(request,'doctor_templates/prescription.html',context)


def update_item(request,booking_id):
    if request.method == 'POST':

        item = Prescription.objects.get(id = booking_id)
        item.diagnosis = request.POST['p_diagnosis']
        item.medication_name = request.POST['p_name']
        item.purpose = request.POST['p_purpose']
        item.dosage = request.POST['p_dosage']
        item.route = request.POST['p_route']
        item.frequency = request.POST['p_frequency']
        item.save()
        messages.success(request, 'prescription Updated Successfully')
        
        
    return redirect('doctor:prescription', booking_id=item.booking_id)

@auth_doctor
def doctor_consultation(request):
    
    consultation_detail = Consultation.objects.filter(doctor_id = request.session['doctor'])

    
    return render(request,'doctor_templates/consultation.html',{'consultation_details':consultation_detail})

def update_consultation_status(request):
    if request.method == 'POST':
        consultation_id = request.POST['consultation_id']
        new_status = request.POST['new_status']
        consultation = Consultation.objects.get(id=consultation_id)
        consultation.status = new_status
        consultation.save()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method'})



def doctor_logout(request):
    if 'doctor' in request.session:
        request.session.pop('doctor')
    return redirect('common_app:home')

doctor/templates/doctor_templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <!--<title> Responsiive Admin Dashboard | CodingLab </title>-->
    <link rel="stylesheet" href="style.css">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">

    <!-- <link rel="stylesheet" href="{% static 'css/style_base.css' %}"> -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.6.3.js"
        integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <style>
        /* Googlefont Poppins CDN Link */
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        .sidebar {
            position: fixed;
            height: 100%;
            width: 240px;
            background: #0A2558;
            transition: all 0.5s ease;
        }

        .navbar-brand {
            font-size: 23px;
            margin-left: 5px;
            color: #fff;
            font-weight: bold;
        }

        .sidebar.active {
            width: 60px;
        }

        .sidebar .logo-details {
            height: 80px;
            display: flex;
            align-items: center;
        }

        .sidebar .logo-details i {
            font-size: 28px;
            font-weight: 500;
            color: #fff;
            min-width: 60px;
            text-align: center
        }

        .sidebar .logo-details .logo_name {
            color: #fff;
            font-size: 24px;
            font-weight: 500;
        }

        .sidebar .nav-links {
            margin-top: 10px;
        }

        .sidebar .nav-links li {
            position: relative;
            list-style: none;
            height: 50px;
        }

        .sidebar .nav-links li a {
            height: 100%;
            width: 100%;
            display: flex;
            align-items: center;
            text-decoration: none;
            transition: all 0.4s ease;
        }

        .sidebar .nav-links li a.active {
            background: #081D45;
        }

        .sidebar .nav-links li a:hover {
            background: #081D45;
        }

        .sidebar .nav-links li i {
            min-width: 60px;
            text-align: center;
            font-size: 18px;
            color: #fff;
        }

        .sidebar .nav-links li a .links_name {
            color: #fff;
            font-size: 15px;
            font-weight: 400;
            white-space: nowrap;
        }

        .sidebar .nav-links .log_out {
            position: absolute;
            bottom: 0;
            width: 100%;
        }

        .home-section {
            position: relative;
            background: #f5f5f5;
            min-height: 100vh;
            width: calc(100% - 240px);
            left: 240px;
            transition: all 0.5s ease;
        }

        .sidebar.active~.home-section {
            width: calc(100% - 60px);
            left: 60px;
        }

        .home-section nav {
            display: flex;
            justify-content: space-between;
            height: 80px;
            background: #fff;
            display: flex;
            align-items: center;
            position: fixed;
            width: calc(100% - 240px);
            left: 240px;
            z-index: 100;
            padding: 0 20px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
            transition: all 0.5s ease;
        }

        .sidebar.active~.home-section nav {
            left: 60px;
            width: calc(100% - 60px);
        }

        .home-section nav .sidebar-button {
            display: flex;
            align-items: center;
            font-size: 24px;
            font-weight: 500;
        }

        nav .sidebar-button i {
            font-size: 35px;
            margin-right: 10px;
        }

        .home-section nav .search-box {
            position: relative;
            height: 50px;
            max-width: 550px;
            width: 100%;
            margin: 0 20px;
        }

        nav .search-box input {
            height: 100%;
            width: 100%;
            outline: none;
            background: #F5F6FA;
            border: 2px solid #EFEEF1;
            border-radius: 6px;
            font-size: 18px;
            padding: 0 15px;
        }

        nav .search-box .bx-search {
            position: absolute;
            height: 40px;
            width: 40px;
            background: #2697FF;
            right: 5px;
            top: 50%;
            transform: translateY(-50%);
            border-radius: 4px;
            line-height: 40px;
            text-align: center;
            color: #fff;
            font-size: 22px;
            transition: all 0.4 ease;
        }

        .home-section nav .profile-details {
            display: flex;
            align-items: center;
            background: #F5F6FA;
            border: 2px solid #EFEEF1;
            border-radius: 6px;
            height: 50px;
            min-width: 190px;
            padding: 0 15px 0 2px;
        }

        nav .profile-details img {
            height: 40px;
            width: 40px;
            border-radius: 6px;
            object-fit: cover;
        }

        nav .profile-details .admin_name {
            font-size: 15px;
            font-weight: 500;
            color: #333;
            margin: 0 10px;
            white-space: nowrap;
        }

        nav .profile-details i {
            font-size: 25px;
            color: #333;
        }

        .home-section .home-content {
            position: relative;
            padding-top: 104px;
        }



        /* Responsive Media Query */
        @media (max-width: 1240px) {
            .sidebar {
                width: 60px;
            }

            .sidebar.active {
                width: 220px;
            }

            .home-section {
                width: calc(100% - 60px);
                left: 60px;
            }

            .sidebar.active~.home-section {
                /* width: calc(100% - 220px); */
                overflow: hidden;
                left: 220px;
            }

            .home-section nav {
                width: calc(100% - 60px);
                left: 60px;
            }

            .sidebar.active~.home-section nav {
                width: calc(100% - 220px);
                left: 220px;
            }
        }

        @media (max-width: 1150px) {
            .home-content .sales-boxes {
                flex-direction: column;
            }

            .home-content .sales-boxes .box {
                width: 100%;
                overflow-x: scroll;
                margin-bottom: 30px;
            }

            .home-content .sales-boxes .top-sales {
                margin: 0;
            }
        }

        @media (max-width: 1000px) {
            .overview-boxes .box {
                width: calc(100% / 2 - 15px);
                margin-bottom: 15px;
            }
        }

        @media (max-width: 700px) {

            nav .sidebar-button .dashboard,
            nav .profile-details .admin_name,
            nav .profile-details i {
                display: none;
            }

            .home-section nav .profile-details {
                height: 50px;
                min-width: 40px;
            }

            .home-content .sales-boxes .sales-details {
                width: 560px;
            }
        }

        @media (max-width: 550px) {
            .overview-boxes .box {
                width: 100%;
                margin-bottom: 15px;
            }

            .sidebar.active~.home-section nav .profile-details {
                display: none;
            }
        }

        @media (max-width: 400px) {
            .sidebar {
                width: 0;
            }

            .sidebar.active {
                width: 60px;
            }

            .home-section {
                width: 100%;
                left: 0;
            }

            .sidebar.active~.home-section {
                left: 60px;
                width: calc(100% - 60px);
            }

            .home-section nav {
                width: 100%;
                left: 0;
            }

            .sidebar.active~.home-section nav {
                left: 60px;
                width: calc(100% - 60px);
            }
        }
    </style>
    {% block header %}

    {% endblock %}

    <title>{% block title %}base{% endblock %}</title>
</head>

<body>
    <div class="sidebar" style="background-color: indigo;">
        <div class="logo-details">

            <h6 class="navbar-brand "><span class="text-danger">National</span>&nbsp;
                Hospital
            </h6>
        </div>
        <ul class="nav-links" style="    margin-left: -30px;">
            <li>
                <a href="{% url 'doctor:index' %}" class="active">
                    <i class='bx bx-grid-alt'></i>
                    <span class="links_name">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{% url 'doctor:patient_page' %}">
                    <i class="bi bi-person-circle"></i>
                    <span class="links_name">Patient</span>
                </a>
            </li>

            <li>
                <a href="{% url 'doctor:appointments' %}">
                    <i class="bi bi-check2-circle"></i>
                    <span class="links_name">Appointment</span>
                </a>
            </li>

            <li>
                <a href="{% url 'doctor:consultation' %}">
                    <i class="bi bi-calendar-check"></i>
                    <span class="links_name">Your Consulting Details</span>
                </a>
            </li>
            <li>
                <a href="{% url 'doctor:change_password' %}">
                    <i class="bi bi-person-lock"></i>
                    <span class="links_name">Change Password</span>
                </a>
            </li>
            <li>
                <a href="{% url 'doctor:doctor_profile' %}">
                    <i class='bx bx-book-alt'></i>
                    <span class="links_name">Update Profile</span>
                </a>
            </li>

            <li class="log_out">
                <a href="{% url 'doctor:doctor_logout' %}">
                    <i class='bx bx-log-out'></i>
                    <span class="links_name">Logout</span>
                </a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <nav>
            <div class="sidebar-button">
                <i class='bx bx-menu sidebarBtn'></i>
                <span class="dashboard">Doctor Dashboard</span>
            </div>
            
            {% block details %}

           
            {% endblock %}

        </nav>



        {% block content %}
        {% endblock %}




    </section>

    <script>
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".sidebarBtn");
        sidebarBtn.onclick = function () {
            sidebar.classList.toggle("active");
            if (sidebar.classList.contains("active")) {
                sidebarBtn.classList.replace("bx-menu", "bx-menu-alt-right");
            } else
                sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
        }
    </script>

</body>

</html>

doctor/templates/doctor_templates/consultation.html
{% extends 'doctor_templates/base.html' %}
{% load static %}

{% block header %}
<style>
    table {
        border-collapse: collapse;
        width: 100%;

    }

    th,
    td {
        text-align: left;
        padding: 8px;


    }

    tr:nth-child(even) {

        font-size: 17px;
        font-weight: 500;
        background-color: cadetblue;
        color: ivory;

    }

    .tableHead {
        background-color: darkblue;
        color: #fff;
        height: 53px;
        border: 1px solid #fff;
    }

    .tableHead th {
        border: 1px solid #fff;
    }

    .tableBody td {
        border: 1px solid #fff;
    }
</style>
{% endblock %}

{% block title %}Doctor Home{% endblock %}
{% block content %}

<br><br><br><br><br>
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Your Consultation Time Table.
                    <hr>
                </h3>
            </div>
            <div class="row">
                <div class="container-fluid">
                    <div style="overflow-x: auto;">

                        <table>

                            <tr class="tableHead">

                                <th>Day</th>
                                <th>Time</th>
                                <th>Status</th>
                                <th>Action</th>
                                <th></th>
                            </tr>
                            {% for consult in consultation_details %}
                            <form method="POST">
                                {% csrf_token %}
                                <tr class="tableBody" id="consult{{consult.id}}">
                                    <td>{{consult.day }}</td>
                                    <td>{{consult.time}}</td>
                                    <td>{{consult.status}}</td>

                                    <td><button class="btn btn-danger" name='unavailable' type="button"
                                        onclick="updateConsultationStatus('{{consult.id}}', 'unavailable')">Not Available</button>
                                        <span style="margin-left: 5px;">
                                        <button class="btn btn-success" name='available' type="button"
                                            onclick="updateConsultationStatus('{{consult.id}}', 'available')">Available</button>
                                        </span>

                                    </td>

                                    <td><input type="hidden" name="consultation_id" value="{{consult.id}}"></td>
                                </tr>

                            </form>

                            {% empty %}
                            <h4 class="notFound text-center text-danger">No doctor record found.</h4>

                            {% endfor %}
                        </table>
                    </div>


                </div>
            </div>
        </div>
    </div>
</section>


<script>
    function updateConsultationStatus(consultationId, newStatus) {
            $.ajax({
                type: "POST",
                url: "{% url 'doctor:update_consultation_status' %}",
                data: {
                    'consultation_id': consultationId,
                    'new_status': newStatus,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function (data) {
                    // Update the status of the relevant row
                    $('#consult' + consultationId + ' td:eq(2)').text(newStatus);
                },
                error: function (xhr, textStatus, errorThrown) {
                    alert('Error updating consultation status: ' + errorThrown);
                }
            });
        }
</script>


{% endblock %}

doctor/templates/doctor_templates/patient_page.html
{% extends 'doctor_templates/base.html' %}
{% load static %}

{% block header %}
<style>
    .card {
        align-items: center;
        justify-content: center;
        max-width: 400px;
        background-color: firebrick;
        color: #fff;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        transition: transform 0.3s ease-in-out;
    }
    .card:hover  {
    transform: scale(1.1);
    }
</style>
{% endblock %}

{% block title %}View Appointments{% endblock %}
{% block content %}

<br><br><br><br><br>

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a href="{% url 'doctor:patient_record' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <div style="    font-size: 95px;margin-left: 15px;">
                            <i class='bi bi-person-circle'></i>

                        </div>
                        <div>
                            <h5>Patient Consulted</h5>
                        </div>



                    </div>
                </a>
            </div>

            <div class="col-md-4">
                <a href="{% url 'doctor:patient_booked' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <div style="    font-size: 95px;margin-left: 15px;">
                            <i class="bi bi-card-checklist"></i>

                        </div>
                        <div>
                            <h5>Booked Patients</h5>
                        </div>



                    </div>
                </a>
            </div>
        </div>
    </div>

</section>


{% endblock %}