admin_app/urls.py
from django.urls import path
from . import views
app_name='admin_app'


urlpatterns=[

    path('index',views.admin_app_index,name='index'),
    path('view_messages',views.admin_app_view_messages,name='view_messages'),
    path('clear_all', views.clear_all, name='clear_all'),

    path('doctor_page',views.admin_app_doctor_page,name='doctor_page'),
    path('adm_departments',views.admin_app_adm_departments,name='adm_departments'),
    path('department/remove/<int:d_id>',views.remove_department,name='remove_department'),
    path('add_department',views.admin_app_add_department,name='add_departments'),
    path('change_department/<int:e_id>',views.admin_app_change_department,name='change_departments'),
    path('approve_doctor',views.admin_app_approve_doctor,name='approve_doctor'),
    path('doctor_specialisation',views.admin_app_doctor_specialisation,name='doctor_specialisation'),
    path('doctor_record',views.admin_app_doctor_record,name='doctor_record'),
    path('doctor/remove/<int:d_id>',views.remove_doctor_record,name='remove_doctor'),
    path('register_doctor',views.admin_app_register_doctor,name='register_doctor'),
    path('check_email_doctor',views.check_email_doctor,name='check_email_doctor'),

    path('consultation/<int:d_id>',views.admin_app_consultation,name='consultation'),
    path('check_day/', views.check_day, name='check_day'),
    path('delete_consultation/<int:c_id>/', views.delete_consultation, name='delete_consultation'),
    path('edit_consultation/<int:d_id>/', views.edit_consultation, name='edit_consultation'),
    path('update_consultation/<int:d_id>/',views.update_consultation,name='update_consultation'),
    



    path('patient_page',views.admin_app_patient_page,name='patient_page'),
    path('patient_registered',views.admin_app_patient_registered,name='patient_registered'),
    path('patient_registered/remove/<int:d_id>',views.remove_regpatient_record,name='remove_patient'), 
    path('approve_patient',views.admin_app_approve_patient,name='approve_patient'),
    path('view_patients',views.admin_app_view_patients,name='view_patients'),
    path('consulted_patient',views.admin_app_consulted_patient,name='consulted_patient'),
    path('consulted_patient/remove/<int:p_id>',views.remove_consulted_patient,name='remove_consulted_patient'),
    path('patient_record/remove/<int:p_id>',views.remove_patient_record,name='remove_patient'),
    path('book_patient',views.admin_app_book_patient,name='book_patient'),


    path('appointments',views.admin_app_appointments,name='appointments'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    
  
]

common_app/urls.py
from django.urls import path
from . import views
app_name='common_app'


urlpatterns=[
    path('',views.common_app_index,name='home'),
   
    path('about',views.common_app_about,name='about'),
    path('contact',views.common_app_contact,name='contact'),
    path('patient_click',views.common_app_patient_click,name='patient_click'),
    path('patient_login',views.common_app_patient_login,name='patient_login'),
    path('patient_register',views.common_app_patient_register,name='patient_register'),
    path('doctors_login',views.common_app_doctors_login,name='doctors_login'),
    path('doctors_register',views.common_app_doctors_register,name='doctor_register'),
    path('doc_logincheck/<int:doctor_id>/',views.common_app_doc_logincheck, name='doc_logincheck'),



    path('department',views.common_app_department,name='department'),
    path('doctors',views.common_app_doctors,name='doctors'),
    path('doctor_click',views.common_app_doctor_click,name='doctor_click'),
    path('admin_click',views.common_app_admin_click,name='admin_click'),
    path('admin_register',views.common_app_admin_register,name='admin_register'),
    path('admin_login',views.common_app_admin_login,name='admin_login'),
    
    path('checkemail',views.check_email,name='check_email'),
    path('checkemail_doctor',views.check_email_admin,name='check_email_admin'),
    path('checkemail_admin',views.check_email_doctor,name='check_email_doctor'),

    
]

doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'


urlpatterns=[
    path('base',views.doctor_base,name='base'),
    path('index',views.doctor_index,name='index'),


    path('appointments',views.doctor_appointments,name='appointments'),
   
    path('delete_appointment',views.doctor_delete_appointment,name='delete_appointment'),
    path('remove_appointment/<int:d_id>',views.remove_appointment,name='remove_app'),

    path('patient_page',views.doctor_patient_page,name='patient_page'),
    path('patient_record',views.doctor_patient_record,name='patient_record'),
    path('patient_booked',views.doctor_patient_booked,name='patient_booked'),
  
    path('view_prescription/<int:booking_id>',views.doctor_view_prescription,name='view_prescription'),

    path('change_password',views.doctor_change_password,name='change_password'),
    path('doctor_profile',views.doctor_doctor_profile,name='doctor_profile'),

    path('view_appointment/', views.doctor_view_appointment, name='view_appointment'),
    path('add_prescription/<int:b_id>/',views.add_prescription,name='add_prescription'),
    path('doctor/prescription/<int:booking_id>/',views.doctor_prescription,name='prescription'),
    path('delete_item/<int:booking_id>/',views.delete_item,name='delete_item'),
    path('edit_item/<int:booking_id>/',views.edit_item,name='edit_item'),
    path('update_item/<int:booking_id>/',views.update_item,name='update_item'),
    path('consultation',views.doctor_consultation,name='consultation'),
    path('update_consultation_status',views.update_consultation_status,name='update_consultation_status'),



    path('doctor_logout',views.doctor_logout,name='doctor_logout'),
]

hospital_management/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common_app.urls')),
    path('patient/', include('patient.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('doctor/', include('doctor.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views
app_name='patient'


urlpatterns=[
    path('index',views.patient_index,name='index'),
    path('doc_booking',views.patient_doc_booking,name='booking'),
    path('profile',views.patient_profile,name='profile'),
    path('booked',views.patient_booked,name='booked'),

    path('your_bookings',views.patient_your_bookings,name='your_bookings'),
    path('prescription_list',views.patient_prescription_list,name='prescription_list'),
    path('view_bookings',views.patient_view_bookings,name='view_bookings'),
    path('pat_doctors',views.patient_pat_doctors,name='pat_doctors'),

    path('doctor_search',views.doctorSearchAjax,name='doctor_search'),
    path('searchdoctor',views.searchdoctor,name='searchdoctor'),


    path('view_search_result/<int:d_id>/',views.patient_view_search_result,name='search_result'),
   



    path('consultation_details/<int:consultation_id>/', views.patient_consultation_details, name='consultation_details'),
    path('change_password',views.patient_change_password,name='change_password'),
  
    path('view_prescription/<int:booking_id>/',views.patient_view_prescription,name='view_prescription'),

    path('patient_logout',views.patient_logout,name='patient_logout'),
]

patient/models.py
from django.db import models

from common_app.models import Doctors, Patient

# Create your models here.

class Booking(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE,null=True )
    patient_name = models.CharField(max_length=50)
    patient_email = models.CharField(max_length=40)
    patient_phone = models.BigIntegerField()
    patient_gender = models.CharField(max_length=15)
    birth_date =  models.DateField(null=True)
    patient_age = models.PositiveIntegerField(null=True, blank=True)
    booking_date = models.DateField()
    booking_time = models.TimeField()
    reference_no = models.CharField(max_length=40, default='')
    doctor_name = models.ForeignKey(Doctors,on_delete=models.CASCADE)
    patient_description = models.CharField(max_length=200)
    patient_address = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(max_length=20, default='pending')

    class Meta:
        db_table = 'booking'

patient/views.py
from random import randint
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from admin_app.models import Consultation
from common_app.models import Doctors, Patient
from doctor.models import Prescription
from patient.decorators import auth_patient
from django.http import Http404

from patient.models import Booking
# Create your views here.






@auth_patient
def patient_index(request):
    pat = Patient.objects.filter(id = request.session['patient']).values('patient_name')
    print(pat)
    patient_name = pat[0]['patient_name']
    


    patient_id = request.session['patient']
    booking_view = Booking.objects.filter(patient_id=patient_id).order_by('-id')[0:1]
    
    recent_booking = {}
    for book in booking_view:
        if book.patient_email in recent_booking:
            if book.booking_date > recent_booking[book.patient_email].booking_date:
                recent_booking[book.patient_email] = book
        else:
            recent_booking[book.patient_email] = book
    recent_booking_list = list(recent_booking.values())

    doctor = None
    if recent_booking_list:
        recent_booking = recent_booking_list[0]
        try:
            doctor = Doctors.objects.get(id=recent_booking.doctor_name.id)
        except Doctors.DoesNotExist:
            pass
    print(doctor,'00000000000')
    return render(request,'patient_templates/index.html',{'booking_list':recent_booking_list ,'doctor': doctor,'p_name':patient_name})

@auth_patient
def patient_doc_booking(request):
    
    doctor = None
   
    if request.method == 'POST':
        pname = request.POST['pat_name']
        pemail = request.POST['pat_email']
        pphone = request.POST['pat_phone']
        pgender = request.POST['pat_gender']
        pbirth = request.POST['pat_birth']
        page = request.POST['pat_age']
        pdate = request.POST['pat_date']
        ptime = request.POST['pat_time']
        pdoctor = request.POST['pat_doctor']
        pdescription = request.POST['pat_description']
        paddress = request.POST['pat_address']
        ref_no = 'REF-'+ str(randint(1000,9999))+ pphone[6:]
        doctor = Doctors.objects.get(id=pdoctor)
        
        booking = Booking(patient_name = pname,
                        patient_email = pemail,
                        patient_phone = pphone,
                        patient_gender = pgender,
                        birth_date =pbirth ,
                        patient_age = page, 
                        booking_date = pdate, 
                        booking_time = ptime, doctor_name = doctor, 
                        patient_description = pdescription,
                        patient_address = paddress,
                        reference_no = ref_no,
                        patient_id=request.session['patient'])
        booking.save()
        booking_id = booking.id  # get the ID of the newly created booking
        request.session['booking_id'] = booking_id 
        return redirect("patient:booked")
        

    else:
        doctors = Doctors.objects.filter(status = 'approved') 
        

    
        

    return render(request,'patient_templates/doc_booking.html',{'doctor':doctors} )

@auth_patient
def patient_profile(request):
    msg = ''
    profile = Patient.objects.filter(id = request.session['patient'])
    
    if request.method == 'POST':
        
        new_name = request.POST['name']
        new_phone = request.POST['phone']
        new_address = request.POST['address']
        new_email = request.POST['email']
        patient = Patient.objects.get(id = request.session['patient'])#.update(patient_name = new_name,patient_mobile = new_phone, patient_address = new_address, patient_email = new_email)
        patient.patient_name = new_name
        patient.patient_mobile = new_phone
        patient.patient_address = new_address
        patient.patient_email = new_email

        patient.save()
        msg = "Update Successfully!"


    return render(request,'patient_templates/profile.html',{'profile':profile,'message':msg})
@auth_patient
def patient_booked(request):
    return render(request,'patient_templates/booked.html')


@auth_patient
def patient_your_bookings(request):
    return render(request,'patient_templates/your_bookings.html')
    
@auth_patient
def patient_prescription_list(request):
    patient_id = request.session['patient']
    patient_view = Booking.objects.filter(patient_id=patient_id, status = 'consulted')
    # patient_view = Booking.objects.filter(id = request.session['patient'])
    print(patient_view)
    return render(request,'patient_templates/prescription_list.html',{'views':patient_view})

@auth_patient
def patient_view_bookings(request):
    patient_id = request.session['patient']
    patient_view = Booking.objects.filter(patient_id=patient_id, status__in=['pending', 'booked'])
    # patient_view = Booking.objects.filter(id = request.session['patient'])
    print(patient_view)
    return render(request,'patient_templates/view_bookings.html',{'views':patient_view})

@auth_patient
def patient_pat_doctors(request):
    doctor = Doctors.objects.filter(status = 'approved')
    return render(request,'patient_templates/pat_doctors.html',{'doctor':doctor})

def doctorSearchAjax(request):
    doctors = Doctors.objects.filter(status = 'approved').values_list('doctor_name', flat=True)
    doctorList = list(doctors)

    return JsonResponse(doctorList, safe=False)

def searchdoctor(request):
    if request.method == 'POST':
        searchedterm = request.POST.get('doctorsearch')
        if searchedterm == "":
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            doct = Doctors.objects.filter(doctor_name = searchedterm).first()

            if doct:
                return redirect(f'/patient/view_search_result/{doct.id}/') # f formatted string
    return redirect(request.META.get('HTTP_REFERER'))

@auth_patient
def patient_view_search_result(request, d_id):
    doctor = Doctors.objects.get(id=d_id)
    return render(request,'patient_templates/view_search_result.html',{'doc':doctor})



@auth_patient
def patient_consultation_details(request, consultation_id):

    consultation = Consultation.objects.filter(doctor_id=consultation_id).order_by('id')
    doctor = Doctors.objects.filter(id = consultation_id).values('doctor_name')[0]['doctor_name']
    print(doctor)
    return render(request, 'patient_templates/consultation_details.html', {'details': consultation,'doctor_name':doctor})

@auth_patient
def patient_change_password(request):
    error_msg = ''
    success_msg = ''

    if request.method == 'POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        if new_password == confirm_password:
            if len(new_password) >= 8:
                patient = Patient.objects.get(id = request.session['patient'])
                if patient.patient_password == old_password:

                    patient.patient_password = new_password
                    patient.save()
                    success_msg = 'Password changed successfully'
                else:
                    error_msg = 'Incorrect Password'
            else:
                error_msg = 'Password should be 8 charecters long'
            
        else:
            error_msg = 'Password doesn\'t match'
    
    return render(request,'patient_templates/change_password.html',{'error_message' : error_msg, 'success_message': success_msg})



@auth_patient
def patient_view_prescription(request,booking_id):
    booked_patient = Booking.objects.get(id=booking_id)
    
    prescript = Prescription.objects.filter(booking_id=booking_id)
    return render(request,'patient_templates/view_prescription.html',{'pre':prescript,'book':booked_patient})




def patient_logout(request):
    if 'patient' in request.session:
        request.session.pop('patient')
    return redirect('common_app:home')

patient/templates/patient_templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <!--<title> Responsive Admin Dashboard | CodingLab </title>-->
    <link rel="stylesheet" href="style.css" />
    <!-- Boxicons CDN Link -->
    <link
      href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
      rel="stylesheet"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" />

    <!-- <link rel="stylesheet" href="{% static 'css/style_base.css' %}"> -->

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
    />

    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v6.0.0-beta1/css/all.css"
    />

    <link
      rel="stylesheet"
      href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css"
    />

    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script
      src="https://code.jquery.com/jquery-3.6.3.js"
      integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM="
      crossorigin="anonymous"
    ></script>

    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <style>
      /* Googlefont Poppins CDN Link */
      @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap");

      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: "Poppins", sans-serif;
      }

      .sidebar {
        position: fixed;
        height: 100%;
        width: 240px;
        background: #0a2558;
        transition: all 0.5s ease;
      }

      .navbar-brand {
        font-size: 24px;
        margin-left: 5px;
        color: #fff;
        font-weight: bold;
      }

      .sidebar.active {
        width: 60px;
      }

      .sidebar .logo-details {
        height: 80px;
        display: flex;
        align-items: center;
      }

      .sidebar .logo-details i {
        font-size: 28px;
        font-weight: 500;
        color: #fff;
        min-width: 60px;
        text-align: center;
      }

      .sidebar .logo-details .logo_name {
        color: #fff;
        font-size: 24px;
        font-weight: 500;
      }

      .sidebar .nav-links {
        margin-top: 10px;
      }

      .sidebar .nav-links li {
        position: relative;
        list-style: none;
        height: 50px;
      }

      .sidebar .nav-links li a {
        height: 100%;
        width: 100%;
        display: flex;
        align-items: center;
        text-decoration: none;
        transition: all 0.4s ease;
      }

      .sidebar .nav-links li a.active {
        background: #081d45;
      }

      .sidebar .nav-links li a:hover {
        background: #081d45;
      }

      .sidebar .nav-links li i {
        min-width: 60px;
        text-align: center;
        font-size: 18px;
        color: #fff;
      }

      .sidebar .nav-links li a .links_name {
        color: #fff;
        font-size: 15px;
        font-weight: 400;
        white-space: nowrap;
      }

      .sidebar .nav-links .log_out {
        position: absolute;
        bottom: 0;
        width: 100%;
      }

      .home-section {
        position: relative;
        background: #f5f5f5;
        min-height: 100vh;
        width: calc(100% - 240px);
        left: 240px;
        transition: all 0.5s ease;
      }

      .sidebar.active ~ .home-section {
        width: calc(100% - 60px);
        left: 60px;
      }

      .home-section nav {
        display: flex;
        justify-content: space-between;
        height: 80px;
        background: #fff;
        display: flex;
        align-items: center;
        position: fixed;
        width: calc(100% - 240px);
        left: 240px;
        z-index: 100;
        padding: 0 20px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
        transition: all 0.5s ease;
      }

      .sidebar.active ~ .home-section nav {
        left: 60px;
        width: calc(100% - 60px);
      }

      .home-section nav .sidebar-button {
        display: flex;
        align-items: center;
        font-size: 24px;
        font-weight: 500;
      }

      nav .sidebar-button i {
        font-size: 35px;
        margin-right: 10px;
      }

      .home-section nav .search-box {
        position: relative;
        height: 50px;
        max-width: 550px;
        width: 100%;
        margin: 0 20px;
      }

      nav .search-box input {
        height: 100%;
        width: 100%;
        outline: none;
        background: #f5f6fa;
        border: 2px solid #efeef1;
        border-radius: 6px;
        font-size: 18px;
        padding: 0 15px;
      }

      nav .search-box .bx-search {
        position: absolute;
        height: 40px;
        width: 40px;
        background: #2697ff;
        right: 5px;
        top: 50%;
        transform: translateY(-50%);
        border-radius: 4px;
        line-height: 40px;
        text-align: center;
        color: #fff;
        font-size: 22px;
        transition: all 0.4 ease;
      }

      .home-section nav .profile-details {
        display: flex;
        align-items: center;
        background: #f5f6fa;
        border: 2px solid #efeef1;
        border-radius: 6px;
        height: 50px;
        min-width: 190px;
        padding: 0 15px 0 2px;
      }

      nav .profile-details img {
        height: 40px;
        width: 40px;
        border-radius: 6px;
        object-fit: cover;
      }

      nav .profile-details .admin_name {
        font-size: 15px;
        font-weight: 500;
        color: #333;
        margin: 0 10px;
        white-space: nowrap;
      }

      nav .profile-details i {
        font-size: 25px;
        color: #333;
      }

      .home-section .home-content {
        position: relative;
        padding-top: 104px;
      }

      /* Responsive Media Query */
      @media (max-width: 1240px) {
        .sidebar {
          width: 60px;
        }

        .sidebar.active {
          width: 220px;
        }

        .home-section {
          width: calc(100% - 60px);
          left: 60px;
        }

        .sidebar.active ~ .home-section {
          /* width: calc(100% - 220px); */
          overflow: hidden;
          left: 220px;
        }

        .home-section nav {
          width: calc(100% - 60px);
          left: 60px;
        }

        .sidebar.active ~ .home-section nav {
          width: calc(100% - 220px);
          left: 220px;
        }
      }

      @media (max-width: 1150px) {
        .home-content .sales-boxes {
          flex-direction: column;
        }

        .home-content .sales-boxes .box {
          width: 100%;
          overflow-x: scroll;
          margin-bottom: 30px;
        }

        .home-content .sales-boxes .top-sales {
          margin: 0;
        }
      }

      @media (max-width: 1000px) {
        .overview-boxes .box {
          width: calc(100% / 2 - 15px);
          margin-bottom: 15px;
        }
      }

      @media (max-width: 700px) {
        nav .sidebar-button .dashboard,
            nav .profile-details .admin_name,
            /* nav .profile-details i {
                display: none;
            } */

            .home-section nav .profile-details {
          height: 50px;
          min-width: 40px;
        }

        .home-content .sales-boxes .sales-details {
          width: 560px;
        }
      }

      @media (max-width: 600px) {
        nav .sidebar-button .dashboard {
          font-size: 17px;
          margin-top: 23px;
        }
      }

      @media (max-width: 550px) {
        .overview-boxes .box {
          width: 100%;
          margin-bottom: 15px;
        }

        /* .sidebar.active~.home-section nav .profile-details {
                display: none;
            } */
        nav .profile-details i {
          font-size: 15px;
          color: #333;
        }

        nav .sidebar-button .dashboard {
          font-size: 17px;
          margin-top: 23px;
        }
      }

      @media (max-width: 400px) {
        .sidebar {
          width: 0;
        }

        .sidebar.active {
          width: 60px;
        }

        .home-section {
          width: 100%;
          left: 0;
        }

        .sidebar.active ~ .home-section {
          left: 60px;
          width: calc(100% - 60px);
        }

        .home-section nav {
          width: 100%;
          left: 0;
        }

        .sidebar.active ~ .home-section nav {
          left: 60px;
          width: calc(100% - 60px);
        }
      }
    </style>
    {% block header %} {% endblock %}

    <title>{% block title %}base{% endblock %}</title>
  </head>

  <body>
    <div class="sidebar" id="sidebar">
      <div class="logo-details">
        <h6 class="navbar-brand">
          <span class="text-danger">National</span>&nbsp; Hospital
        </h6>
      </div>
      <ul class="nav-links" style="margin-left: -30px">
        <li>
          <a href="{% url 'patient:index' %}" class="active">
            <i class="bx bx-grid-alt"></i>
            <span class="links_name">Dashboard</span>
          </a>
        </li>
        <li>
          <a href="{% url 'patient:booking' %}">
            <i class="bi bi-list-check"></i>
            <span class="links_name">Bookings</span>
          </a>
        </li>
        <li>
          <a href="{% url 'patient:pat_doctors' %}">
            <i class="bi bi-person-circle"></i>
            <span class="links_name">Doctors</span>
          </a>
        </li>
        <li>
          <a href="{% url 'patient:your_bookings' %}">
            <i class="bx bx-pie-chart-alt-2"></i>
            <span class="links_name">View Bookings</span>
          </a>
        </li>
        <li>
          <a href="{% url 'patient:change_password' %}">
            <i class="bx bx-lock"></i>
            <span class="links_name">Change Password</span>
          </a>
        </li>
        <li>
          <a href="{% url 'patient:profile' %}">
            <i class="bi bi-folder-plus"></i>
            <span class="links_name">Update Profile</span>
          </a>
        </li>

        <li class="log_out">
          <a href="{% url 'patient:patient_logout' %}">
            <i class="bx bx-log-out"></i>
            <span class="links_name">Log out</span>
          </a>
        </li>
      </ul>
    </div>
    <section class="home-section">
      <nav id="navbar">
        <div class="sidebar-button">
          <i class="bx bx-menu sidebarBtn"></i>
          <span class="dashboard">Patient Dashboard</span>
        </div>

        {% block details %} {% endblock %}
      </nav>

      {% block content %}{% endblock %}

      <!-- <footer>
            <div style="background-color: black; height: 50px;">

            </div>
            
        </footer> -->
    </section>

    <script src="https://pro.fontawesome.com/releases/v6.0.0-beta1/js/all.js"></script>

    <script>
      let sidebar = document.querySelector(".sidebar");
      let sidebarBtn = document.querySelector(".sidebarBtn");
      sidebarBtn.onclick = function () {
        sidebar.classList.toggle("active");
        if (sidebar.classList.contains("active")) {
          sidebarBtn.classList.replace("bx-menu", "bx-menu-alt-right");
        } else sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
      };
    </script>
  </body>
</html>

patient/templates/patient_templates/prescription_list.html
{% extends 'patient_templates/base.html' %} {% load static %} {% block header %}
<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }

  th,
  td {
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    font-size: 17px;
    font-weight: 500;
    background-color: sandybrown;
    color: ivory;
  }

  .tableHead {
    background-color: brown;
    color: #fff;
    height: 53px;
  }

  .docImage img {
    width: 85px;
    border-radius: 9px;
    border: 1px solid #fff;
  }
  .notFound {
    text-align: center;
    color: red;
  }
</style>
{% endblock %} {% block title %}View Bookind=g{% endblock %} {% block content %}

<br /><br /><br /><br /><br />

<section class="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h4 style="margin-top: 20px; margin-bottom: 30px">
          Your Prescription History.
          <hr />
        </h4>
      </div>
      <div class="container-fluid">
        <div style="overflow-x: auto">
          <table>
            <tr class="tableHead">
              <th>SL.No</th>
              <th>Doctor Name</th>
              <th>Patient Name</th>
              <th>Description</th>
              <th>Date</th>
              <th>Time</th>
              <th>Status</th>
            </tr>
            {% for p in views %}

            <tr>
              <td>{{ forloop.counter }}</td>

              <td>{{p.doctor_name.doctor_name}}</td>
              <td>{{p.patient_name}}</td>
              <td>{{p.patient_description}}</td>
              <td>{{p.booking_date}}</td>

              <td>{{p.booking_time}}</td>

              <td>
                <span class="bg-success text-white">{{ p.status }}</span>
                <a
                  href="{% url 'patient:view_prescription' p.id %}"
                  class="btn btn-sm btn-info"
                  style="float: right; color: #fff"
                  >View Prescription</a
                >
              </td>
            </tr>
            {% empty %}
            <h4 class="notFound">No Booking found.</h4>

            {% endfor %}
          </table>
        </div>
      </div>
      <div>
        <a
          href="{% url 'patient:your_bookings' %}"
          style="float: left; margin-top: 7px"
          class="btn btn-danger"
        >
          Back</a
        >
      </div>
    </div>
  </div>
</section>

{% endblock %}