admin_app/urls.py
from django.urls import path
from . import views
app_name='admin_app'


urlpatterns=[

    path('index',views.admin_app_index,name='index'),
    path('view_messages',views.admin_app_view_messages,name='view_messages'),
    path('clear_all', views.clear_all, name='clear_all'),

    path('doctor_page',views.admin_app_doctor_page,name='doctor_page'),
    path('adm_departments',views.admin_app_adm_departments,name='adm_departments'),
    path('department/remove/<int:d_id>',views.remove_department,name='remove_department'),
    path('add_department',views.admin_app_add_department,name='add_departments'),
    path('change_department/<int:e_id>',views.admin_app_change_department,name='change_departments'),
    path('approve_doctor',views.admin_app_approve_doctor,name='approve_doctor'),
    path('doctor_specialisation',views.admin_app_doctor_specialisation,name='doctor_specialisation'),
    path('doctor_record',views.admin_app_doctor_record,name='doctor_record'),
    path('doctor/remove/<int:d_id>',views.remove_doctor_record,name='remove_doctor'),
    path('register_doctor',views.admin_app_register_doctor,name='register_doctor'),
    path('check_email_doctor',views.check_email_doctor,name='check_email_doctor'),

    path('consultation/<int:d_id>',views.admin_app_consultation,name='consultation'),
    path('check_day/', views.check_day, name='check_day'),
    path('delete_consultation/<int:c_id>/', views.delete_consultation, name='delete_consultation'),
    path('edit_consultation/<int:d_id>/', views.edit_consultation, name='edit_consultation'),
    path('update_consultation/<int:d_id>/',views.update_consultation,name='update_consultation'),
    



    path('patient_page',views.admin_app_patient_page,name='patient_page'),
    path('patient_registered',views.admin_app_patient_registered,name='patient_registered'),
    path('patient_registered/remove/<int:d_id>',views.remove_regpatient_record,name='remove_patient'), 
    path('approve_patient',views.admin_app_approve_patient,name='approve_patient'),
    path('view_patients',views.admin_app_view_patients,name='view_patients'),
    path('consulted_patient',views.admin_app_consulted_patient,name='consulted_patient'),
    path('consulted_patient/remove/<int:p_id>',views.remove_consulted_patient,name='remove_consulted_patient'),
    path('patient_record/remove/<int:p_id>',views.remove_patient_record,name='remove_patient'),
    path('book_patient',views.admin_app_book_patient,name='book_patient'),


    path('appointments',views.admin_app_appointments,name='appointments'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    
  
]

doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'


urlpatterns=[
    path('base',views.doctor_base,name='base'),
    path('index',views.doctor_index,name='index'),


    path('appointments',views.doctor_appointments,name='appointments'),
   
    path('delete_appointment',views.doctor_delete_appointment,name='delete_appointment'),
    path('remove_appointment/<int:d_id>',views.remove_appointment,name='remove_app'),

    path('patient_page',views.doctor_patient_page,name='patient_page'),
    path('patient_record',views.doctor_patient_record,name='patient_record'),
    path('patient_booked',views.doctor_patient_booked,name='patient_booked'),
  
    path('view_prescription/<int:booking_id>',views.doctor_view_prescription,name='view_prescription'),

    path('change_password',views.doctor_change_password,name='change_password'),
    path('doctor_profile',views.doctor_doctor_profile,name='doctor_profile'),

    path('view_appointment/', views.doctor_view_appointment, name='view_appointment'),
    path('add_prescription/<int:b_id>/',views.add_prescription,name='add_prescription'),
    path('doctor/prescription/<int:booking_id>/',views.doctor_prescription,name='prescription'),
    path('delete_item/<int:booking_id>/',views.delete_item,name='delete_item'),
    path('edit_item/<int:booking_id>/',views.edit_item,name='edit_item'),
    path('update_item/<int:booking_id>/',views.update_item,name='update_item'),
    path('consultation',views.doctor_consultation,name='consultation'),
    path('update_consultation_status',views.update_consultation_status,name='update_consultation_status'),



    path('doctor_logout',views.doctor_logout,name='doctor_logout'),
]

hospital_management/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common_app.urls')),
    path('patient/', include('patient.urls')),
    path('admin_app/', include('admin_app.urls')),
    path('doctor/', include('doctor.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin_app/models.py
from django.db import models

from common_app.models import Doctors

# Create your models here.





class Consultation(models.Model) : 

    doctor = models.ForeignKey(Doctors, on_delete = models.CASCADE)
    day = models.CharField(max_length = 20)
    time = models.CharField(max_length = 20)
    status = models.CharField(max_length = 20, default = 'available')
    
    class Meta :
        db_table = 'consult'

admin_app/views.py
from random import randint
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy
from admin_app.decorators import auth_admin
from admin_app.models import Consultation

from common_app.models import Admin, Contact, Departments, Doctors, Patient
from patient.models import Booking
from django.contrib import messages


# Create your views here.

@auth_admin
def admin_app_index(request):
    admin = Admin.objects.filter(id = request.session['admin']).values('admin_name')
    
    admin_name = admin[0]['admin_name']
    doctor = Doctors.objects.all().count()   
    patient = Patient.objects.all().count() # customer count
    booking = Booking.objects.all().count()



    doctor_list = Doctors.objects.all().order_by('-id')[0:5]
    recent_doctors = {}
    for reg in doctor_list:
        if reg.doctor_email in recent_doctors:
            if reg.id > recent_doctors[reg.doctor_email].id:

                 recent_doctors[reg.doctor_email] = reg
        else:
            recent_doctors[reg.doctor_email] = reg
    reg_doctors_list = list(recent_doctors.values())


    patient_list = Patient.objects.all().order_by('-id')[0:10]
    recent_patients = {}
    for regs in patient_list:
        if regs.patient_email in recent_patients:
            if regs.id > recent_patients[regs.patient_email].id:

                 recent_patients[regs.patient_email] = regs
        else:
            recent_patients[regs.patient_email] = regs
    reg_patient_list = list(recent_patients.values())
    
    return render(request,'admin_app_templates/index.html',{'patient_count':patient,'doctor_count':doctor,'booking_count':booking, 'reg_doctors_list':reg_doctors_list,'reg_patient_list':reg_patient_list,'admin_name':admin_name})

@auth_admin
def admin_app_view_messages(request):
    message = Contact.objects.all()
    return render(request,'admin_app_templates/view_messages.html',{'message':message})

def clear_all(request):
    clear = Contact.objects.all()
    clear.delete()
    return redirect('admin_app:view_messages')

@auth_admin
def admin_app_doctor_page(request):
    return render(request,'admin_app_templates/doctor_page.html')

@auth_admin
def admin_app_adm_departments(request):
    dept = Departments.objects.all()
    return render(request,'admin_app_templates/adm_departments.html' ,{'department':dept})

@auth_admin
def remove_department(request,d_id):
    dep_list = Departments.objects.get(id = d_id)
    dep_list.delete()
    
    return redirect('admin_app:adm_departments')
# /////////////////////////////////////////////////////////////////////////////////////



@auth_admin
def admin_app_add_department(request):
    msg1 =''
    msg2 =''
    if request.method == 'POST':
        de_name = request.POST['department_name']
        de_description = request.POST['department_description']
        de_image = request.FILES['department_image']

        department_exist = Departments.objects.filter(dep_name = de_name).exists()

        if not department_exist:
            department = Departments(dep_name = de_name, dep_description = de_description, dep_image = de_image)
            department.save()
            msg1 = 'Department added successfully'
    
        else:
            msg2 = 'Department name already exist.'

    return render(request,'admin_app_templates/add_department.html', {'message1':msg1,'message2':msg2})


@auth_admin
def admin_app_change_department(request,e_id):
    msg=''
    error_msg =''
    department = Departments.objects.get(id=e_id)
    if request.method == 'POST':
        dep = Departments.objects.get(id = e_id)
        new_name =  request.POST['department_name']
        new_description =  request.POST['department_description']
        if 'department_image' in request.FILES:
            new_image =  request.FILES['department_image']
            dep.dep_name= new_name
            dep.dep_description = new_description
            dep.dep_image = new_image

        else:
            dep.dep_name= new_name
            dep.dep_description = new_description
        dep.save()
        return redirect('admin_app:adm_departments')
         
    else:
        error_msg = "Not Saved"


    return render(request,'admin_app_templates/change_department.html',{'edit_department':department, 'message':msg, "error_msg":error_msg})

@auth_admin
def admin_app_approve_doctor(request):
    doctor = Doctors.objects.filter(status = 'pending')

    if request.method == 'POST':
        doct_id = request.POST['doctor_id']
        doctors = Doctors.objects.get(id = doct_id)

        if 'approve' in request.POST:
            # logic when approve button clicked
            user_name = randint(1111,9999)
            password = 'sel-' + str(user_name) + str(doctors.doctor_phone)[5:]
            
            doctors.status = 'approved' #sql update query
            doctors.user_name = user_name
            doctors.password = password
          
            doctors.save()
            
           
            mail_subject = "Account Approval"
            message_body = "Hi your account has been approved by Admin, You can now login with username" + str(user_name) + " and temprorary password" + password

            
        if 'reject' in request.POST:

            doctors.status = 'reject' 
            doctors.save()
            
            mail_subject = "Account Rejected"
            message_body = "sorry we cannot approve your request"

        send_mail(
            subject = mail_subject,
            message = message_body,
            from_email = settings.EMAIL_HOST_USER,
            recipient_list= [doctors.doctor_email]
            )
    return render(request,'admin_app_templates/approve_doctor.html',{'doctor_list':doctor})


@auth_admin
def admin_app_doctor_specialisation(request):
    doctor_spec = Doctors.objects.filter(status = 'approved')
    return render(request,'admin_app_templates/doctor_specialisation.html',{'doctor_spec':doctor_spec})

@auth_admin
def admin_app_doctor_record(request):
    if 'q' in request.GET:
        q=request.GET['q']
        doctor_rec = Doctors.objects.filter(doctor_name__icontains=q, status='approved').order_by('doctor_name')
    else:
        doctor_rec = Doctors.objects.filter(status = 'approved')
    return render(request,'admin_app_templates/doctor_record.html',{'doctor':doctor_rec})

@auth_admin
def remove_doctor_record(request,d_id):
    doc_record = Doctors.objects.get(id = d_id)
    doc_record.delete()
    return redirect('admin_app:doctor_record')

@auth_admin
def admin_app_register_doctor(request):
    msg = ''
    if request.method == 'POST':
        d_name = request.POST['doc_name']
        d_email = request.POST['doc_email']
        
        d_phone = request.POST['doc_phone']
        d_address = request.POST['doc_address']
        d_gender = request.POST['doc_gender']

        dep = request.POST['doc_department']
        if 'doc_image' in request.FILES:
            d_image = request.FILES['doc_image']
            
            doctor = Doctors(doctor_name = d_name, doctor_email = d_email, doctor_department_id = dep, doctor_phone = d_phone, doctor_address = d_address, doctor_gender = d_gender, doctor_image = d_image)
        else:
            doctor = Doctors(doctor_name = d_name, doctor_email = d_email, doctor_department_id = dep, doctor_phone = d_phone, doctor_address = d_address, doctor_gender = d_gender)
        user_name = randint(1111, 9999)
        password = 'sel-' + str(user_name) + str(d_phone)[5:]
        
        doctor.status = 'approved'
        doctor.user_name = user_name
        doctor.password = password
        doctor.save()
        msg = 'Registred Successfully'

        mail_subject = "Account Approval"
        message_body = "Hi your account has been approved by Admin, You can now login with username" + str(user_name) + " and temprorary password" + password

        send_mail(
            subject = mail_subject,
            message = message_body,
            from_email = settings.EMAIL_HOST_USER,
            recipient_list= [doctor.doctor_email]
            )
            
    dep = Departments.objects.all()
    return render(request,'admin_app_templates/register_doctor.html',{'departments':dep,'message':msg})

@auth_admin
def check_email_doctor(request): # checking email of admin
    email = request.POST['doc_email']
    print(email)
    email_exist =Doctors.objects.filter(doctor_email=email).exists()
    if not email_exist:
        status = False
    else:
        status = True
    return JsonResponse({'email_exist': status})
@auth_admin
def admin_app_consultation(request, d_id):
    error_msg = ''
    success_msg = ''
    consultation_details = Consultation.objects.filter(doctor = d_id)
    doctor = Doctors.objects.filter(id = d_id).values('doctor_name')[0]['doctor_name']
    if request.method == 'POST':
        consultaion_day = request.POST['consult_day']
        consultaion_time = request.POST['frm_time'] + ' - ' + request.POST['to_time']
        record_exist = Consultation.objects.filter(doctor = d_id, day = consultaion_day, time = consultaion_time).exists()
        if not record_exist :
            new_record = Consultation(doctor_id = d_id,day = consultaion_day, time = consultaion_time)
            new_record.save()
            success_msg = 'Record Added Succesfully'
        else:
            error_msg = 'Record Already Added'
   
    context = {
            'doctor_name': doctor,
            'consultation_details':consultation_details,
            'success_msg':success_msg,
            'error_msg':error_msg
            
            }
    
    return render(request,'admin_app_templates/consultation.html',context)

def check_day(request): # checking consult day and time is repeating or not
    c_day = request.POST.get('consult_day')
    day_exist = Consultation.objects.filter(day=c_day).exists()

admin_app/templates/admin_app_templates/adm_departments.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<!-- <link rel="stylesheet" href="{% static 'css/style_doctors.css' %}"> -->
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<style>
    .content {
        height: 100vh;
    }
</style>
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}
<br><br><br><br>
<section class="content">
    <div class='container'>
        <div class="row">
            <div class="col-lg-12">
                <h4 style="margin-top: 20px;margin-bottom: 30px;">Doctors Departments. <hr> </h4>
                <a href="{% url 'admin_app:add_departments' %}" type="button" class="btn btn-success"
                    style="float: right;margin-bottom: 5px;">+ Add
                    Department</a>
            </div>

            <div class="container" style="overflow-x:auto;">

                <table class="table">
                    <thead class="table-dark">
                        <tr>
                            <th style="width: 100px;">SL.No</th>
                            <th>Departments</th>
                            <th></th>

                        </tr>
                    </thead>
                    {% for d in department %}
                    <tbody style=" background-color: darkgray;font-size: 18px;font-weight: 600;">
                        <tr>
                            <td style="width: 100px;">{{forloop.counter}}</td>
                            <td value="{{d.id}}">{{d.dep_name}}</td>
                            <td>

                                <a href="{% url 'admin_app:remove_department' d.id %}" style="float: right;"
                                    class="btn btn-danger "><i class="fa fa-trash"></i> Remove</a>
                                <a href="{% url 'admin_app:change_departments' d.id %}"
                                    style="float: right;margin-right: 8px;" class="btn btn-danger "><i
                                        class="fa fa-trash"></i> Edit</a>



                            </td>
                        </tr>

                    </tbody>
                    {% endfor %}
                </table>




            </div>
        </div>
        <a href="{% url 'admin_app:doctor_page' %}" style="float: left;" class="btn btn-danger ">
            Back Home</a>


    </div>
    </div>
</section>





{% endblock %}

admin_app/templates/admin_app_templates/consultation.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<!-- <link rel="stylesheet" href="{% static 'css/style_doctors.css' %}"> -->
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<style>
    table {
        border-collapse: collapse;
        width: 100%;

    }

    th,
    td {
        text-align: left;
        padding: 8px;


    }

    tr:nth-child(even) {

        font-size: 17px;
        font-weight: 500;
        background-color: cadetblue;
        color: ivory;

    }

    .tableHead {
        background-color: darkblue;
        color: #fff;
        height: 53px;
        border: 1px solid #fff;
    }

    .tableHead th {
        border: 1px solid #fff;
    }

    .tableBody td {
        border: 1px solid #fff;
    }



    .content {
        margin-top: 40px;
    }

    .success {
        font-size: 18px;
        font-weight: 500;
        margin-top: 5px;
        color: green;
    }

    .error {
        font-size: 18px;
        font-weight: 500;
        margin-top: 5px;
        color: red;
    }
</style>
{% endblock %}

{% block title %}Consultation Details{% endblock %}
{% block content %}
<br><br><br><br>
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Consultation Details.
                    <hr>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h2>{{doctor_name|title}}</h2>
                <div style="margin-top: 25px;">
                    {% if edit_cons %}

                    <form class="form-horizontal" method="POST"
                        action="{% url 'admin_app:update_consultation' edit_cons.id %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label class=" col-sm-2" for="email">Select Day</label>
                            <div class="col-sm-10">
                                <select id="consult_day" name="consult_day" class="form-control" style="width: 200px;">
                                    <option value="{{edit_consult.day}}">{{ edit_cons.day }}</option>
                                    <option>Sunday</option>
                                    <option>Monday</option>
                                    <option>Tuesday</option>
                                    <option>Wednesday</option>
                                    <option>Thursday</option>
                                    <option>Friday</option>
                                    <option>Saturday</option>
                                </select>


                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="pwd">Time:</label>
                            <div class="col-sm-10">

                                <input type="text" id="frm_time" value="{{time1}}" name="frm_time" class="form-control"
                                    style="width: 200px; display: inline;">
                                To
                                <input type="text" id="to_time" value="{{time2}}" name="to_time" class="form-control"
                                    style="width: 200px; display: inline;">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary" style="margin-top: 10px;">Update</button>
                                <p class="success">{{update_message}}</p>

                            </div>
                        </div>
                    </form>
                    {% else %}





                    <form class="form-horizontal" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class=" col-sm-2" for="email">Select Day</label>
                            <div class="col-sm-10">
                                <select id="consult_day" name="consult_day" class="form-control" style="width: 200px;">
                                    <option>Select Day</option>
                                    <option>Sunday</option>
                                    <option>Monday</option>
                                    <option>Tuesday</option>
                                    <option>Wednesday</option>
                                    <option>Thursday</option>
                                    <option>Friday</option>
                                    <option>Saturday</option>
                                </select>
                      
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="pwd">Time:</label>
                            <div class="col-sm-10">
                                <input type="text" id="frm_time" name="frm_time" value="{{time1}}" class="form-control"
                                    style="width: 200px; display: inline;">
                                To
                                <input type="text" id="to_time" name="to_time" value="{{time2}}" class="form-control"
                                    style="width: 200px; display: inline;">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary" style="margin-top: 10px;">Submit</button>
                                <p class="success">{{success_msg}}</p>
                                <p class="error">{{error_msg}}</p>
                                {% for msg in messages %}
                                <div class="p-3 mb-2 bg-success text-white alert alert-{{ message.tags }} alert-dismissible fade show"
                                    role="alert" style="width: 221px;">
                                    {{ msg }}
                                    <button type="submit" class="close" id="submit_btn" onclick="dismissAlert(this)" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endfor %}

                            </div>
                        </div>
                    </form>

                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class='container'>
        <div class="row">

            <div class="container-fluid">
                <div style="overflow-x: auto;">

                    <table>

                        <tr class="tableHead">

                            <th>Day</th>
                            <th>Time</th>
                            <th>Status</th>
                            <th>Action</th>


                        </tr>
                        {% for consult in consultation_details %}
                        <tr class="tableBody">
                            <td>{{ consult.day }}</td>
                            <td>{{consult.time}}</td>
                            <td>{{consult.status}}</td>
                            <td><a href="{% url 'admin_app:edit_consultation' consult.id %}" class="btn btn-primary ">
                                    Edit</a> <span><a href="{% url 'admin_app:delete_consultation' consult.id %}"
                                        class="btn btn-danger "><i class="bi bi-trash"></i> Delete</a></span></td>


                        </tr>
                        {% empty %}
                        <h4 class="notFound text-center text-danger">No doctor record found.</h4>

                        {% endfor %}
                    </table>
                </div>


            </div>
           





        </div>
    </div>



</section>




<script>
    function dismissAlert(button) {
        $(button).parent().fadeOut();
    }
</script>

<script>
$(document).ready(function() {
  $('#consult_day').change(function() {
    var selectedDay = $(this).val();
    $.ajax({
      url: "{% url 'admin_app:check_day' %}",
      type: 'POST',
      data: { consult_day: selectedDay },
      success: function(response) {
        if (response.day_exist) {
          
          $('#error_message').text(selectedDay + ' already exists.');
        } else {
          
          $('#error_message').text('');
        }
      }
    });
  });
});

</script>



{% endblock %}

admin_app/templates/admin_app_templates/patient_page.html
{% extends 'admin_app_templates/base.html' %}
{% load static %}

{% block header %}
<!-- <link rel="stylesheet" href="{% static 'css/style_doctors.css' %}"> -->
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<style>
    .card {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 269px;
        background-color: palevioletred;
        color: #fff;
        letter-spacing: 2px;
        margin-bottom: 15px;
    }

    /* .page-header {
        margin-left: 200px;
        margin-top: 44px;
        margin-right: 50px;
    } */
</style>
{% endblock %}

{% block title %}hello{% endblock %}
{% block content %}
<br><br><br><br>


<div class="page-header pt-3">
    <div class="container">
        <div class="row" style="margin-top: 20px;">


            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'admin_app:view_patients' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <img src="{% static 'images/doctorrec (1).png' %}" class="card-img-top" alt="..."
                            style="    width: 110px;margin-top: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Booked Patient</h5>

                        </div>
                    </div>
                </a>
            </div>

            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'admin_app:consulted_patient' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <img src="{% static 'images/doctorrec (1).png' %}" class="card-img-top" alt="..."
                            style="    width: 110px;margin-top: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Consulted Patient</h5>

                        </div>
                    </div>
                </a>
            </div>

            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'admin_app:book_patient' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <img src="{% static 'images/1430402.png' %}" class="card-img-top" alt="..."
                            style="    width: 110px;margin-top: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Admin Patient</h5>

                        </div>
                    </div>
                </a>
            </div>

            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'admin_app:approve_patient' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <img src="{% static 'images/doctorrec (4).png' %}" class="card-img-top" alt="..."
                            style="    width: 110px;margin-top: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Approve Booking</h5>

                        </div>
                    </div>
                </a>
            </div>

            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'admin_app:patient_registered' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <img src="{% static 'images/doctorrec (2).png' %}" class="card-img-top" alt="..."
                            style="    width: 110px;margin-top: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Registered Patient </h5>

                        </div>
                    </div>
                </a>
            </div>



            <!-- <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'admin_app:adm_departments' %}" style="text-decoration: none;">
                    <div class="card mb-5">
                        <img src="{% static 'images/find.png' %}" class="card-img-top" alt="..."
                            style="    width: 110px;margin-top: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Doctor Departments</h5>

                        </div>
                    </div>
                </a>
            </div> -->




        </div>
    </div>
</div>




{% endblock %}